spring.application.name=Discord Thread Extractor
server.port=8082

# Discord Bot Token - Get from https://discord.com/developers/applications
discord.bot.token=MTQ3NTM3OTk5MDA1MTgxNTUzNg.GSQe_-.JeQdFetBE2K8yJsSLTil29n4HGJepmPG_vYSrY
discord.guild.id=1475403732761055346
discord.thread.id=1475404215420588133

spring.datasource.url=jdbc:mysql://localhost:3306/discord_thread_extractor?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1008
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

